version: '3.9'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
  test:
    build:
      context: .
      dockerfile: Dockerfile.test    
    command: ["npm", "run", "test"]
  e2e:
    build:
      context: .
      dockerfile: Dockerfile.e2e    
    command: ["npm", "run", "e2e"]